#**Machine Learning Lab Practice: CLASSIFICATION**
### **2020년11월04일 (수) 19:00 KST**

###**The Libraries**

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

###**The Dataset & Its Preprocessing**

In [4]:
url="https://raw.githubusercontent.com/junyanyao/ISLR_Python/master/Dataset/Smarket.csv"
smarket=pd.read_csv(url)
smarket

Unnamed: 0  Year   Lag1   Lag2  ...   Lag5   Volume  Today  Direction
0              1  2001  0.381 -0.192  ...  5.010  1.19130  0.959         Up
1              2  2001  0.959  0.381  ... -1.055  1.29650  1.032         Up
2              3  2001  1.032  0.959  ... -2.624  1.41120 -0.623       Down
3              4  2001 -0.623  1.032  ... -0.192  1.27600  0.614         Up
4              5  2001  0.614 -0.623  ...  0.381  1.20570  0.213         Up
...          ...   ...    ...    ...  ...    ...      ...    ...        ...
1245        1246  2005  0.422  0.252  ... -0.285  1.88850  0.043         Up
1246        1247  2005  0.043  0.422  ... -0.584  1.28581 -0.955       Down
1247        1248  2005 -0.955  0.043  ... -0.024  1.54047  0.130         Up
1248        1249  2005  0.130 -0.955  ...  0.252  1.42236 -0.298       Down
1249        1250  2005 -0.298  0.130  ...  0.422  1.38254 -0.489       Down

[1250 rows x 10 columns]

####**Dataset Correlation Matrix**

In [5]:
smarket.corr()

Unnamed: 0      Year      Lag1  ...      Lag5    Volume     Today
Unnamed: 0    1.000000  0.979773  0.035415  ...  0.035025  0.546348  0.035273
Year          0.979773  1.000000  0.029700  ...  0.029788  0.539006  0.030095
Lag1          0.035415  0.029700  1.000000  ... -0.005675  0.040910 -0.026155
Lag2          0.036022  0.030596 -0.026294  ... -0.003558 -0.043383 -0.010250
Lag3          0.038989  0.033195 -0.010803  ... -0.018808 -0.041824 -0.002448
Lag4          0.041437  0.035689 -0.002986  ... -0.027084 -0.048414 -0.006900
Lag5          0.035025  0.029788 -0.005675  ...  1.000000 -0.022002 -0.034860
Volume        0.546348  0.539006  0.040910  ... -0.022002  1.000000  0.014592
Today         0.035273  0.030095 -0.026155  ... -0.034860  0.014592  1.000000

[9 rows x 9 columns]

####**Encoding the Target Variable**

In [19]:
#Response --> Change the value from Up & Down to 1 & 2
y=smarket['Direction'].map({'Up':1,'Down':0})

#Predictors 
x=smarket[['Lag1','Lag2','Lag3','Lag4','Lag5','Volume']]

###**The Models**

####**The Model**

In [20]:
from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier

logreg=LogisticRegression()
lda=LinearDiscriminantAnalysis()
qda=QuadraticDiscriminantAnalysis()
knn=KNeighborsClassifier(n_neighbors=3)

####**The Confusion Matrix**

In [21]:
logreg.fit(x,y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [22]:
from sklearn.metrics import confusion_matrix
y_pred=logreg.predict(x)
confusion_matrix(y,y_pred)

array([[144, 458],
       [141, 507]])

In [23]:
from sklearn.metrics import accuracy_score,precision_score,recall_score
print("The Accuracy Score is: ",accuracy_score(y,y_pred))
print("The Precision Score is: ",precision_score(y,y_pred))
print("The Recall Score is: ",recall_score(y,y_pred))
print("The Mean of Response Variable is: ",np.mean(y))

The Accuracy Score is:  0.5208
The Precision Score is:  0.5253886010362694
The Recall Score is:  0.7824074074074074
The Mean of Response Variable is:  0.5184


####**Train Test Split**

In [24]:
features=['Lag1','Lag2']
train=smarket[smarket['Year']<2005]
test=smarket[smarket['Year']==2005]
x_train=train[features]
y_train=train['Direction'].map({'Up':1, 'Down':0})
x_test=test[features]
y_test=test['Direction'].map({'Up':1, 'Down':0})

####**LOGISTIC REGRESSION**

In [28]:
logreg.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [29]:
y_test_pred=logreg.predict(x_test)
confusion_matrix(y_test,y_test_pred)

array([[ 35,  76],
       [ 35, 106]])

In [30]:
print("The Accuracy Score is: ",accuracy_score(y_test,y_test_pred))
print("The Precision Score is: ",precision_score(y_test,y_test_pred))
print("The Recall Score is: ",recall_score(y_test,y_test_pred))
print("The Mean of Response Variable is: ",np.mean(y_test))

The Accuracy Score is:  0.5595238095238095
The Precision Score is:  0.5824175824175825
The Recall Score is:  0.75177304964539
The Mean of Response Variable is:  0.5595238095238095


####**LINEAR DISCRIMINANT ANALYSIS**

In [31]:
lda.fit(x_train,y_train)

LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage=None,
                           solver='svd', store_covariance=False, tol=0.0001)

In [32]:
y_test_pred=lda.predict(x_test)
confusion_matrix(y_test,y_test_pred)

array([[ 35,  76],
       [ 35, 106]])

In [33]:
print("The Accuracy Score is: ",accuracy_score(y_test,y_test_pred))
print("The Precision Score is: ",precision_score(y_test,y_test_pred))
print("The Recall Score is: ",recall_score(y_test,y_test_pred))
print("The Mean of Response Variable is: ",np.mean(y_test))

The Accuracy Score is:  0.5595238095238095
The Precision Score is:  0.5824175824175825
The Recall Score is:  0.75177304964539
The Mean of Response Variable is:  0.5595238095238095


####**QUADRATIC DISCRIMINANT ANALYSIS**

In [34]:
qda.fit(x_train,y_train)

QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)

In [35]:
y_test_pred=qda.predict(x_test)
confusion_matrix(y_test,y_test_pred)

array([[ 30,  81],
       [ 20, 121]])

In [36]:
print("The Accuracy Score is: ",accuracy_score(y_test,y_test_pred))
print("The Precision Score is: ",precision_score(y_test,y_test_pred))
print("The Recall Score is: ",recall_score(y_test,y_test_pred))
print("The Mean of Response Variable is: ",np.mean(y_test))

The Accuracy Score is:  0.5992063492063492
The Precision Score is:  0.599009900990099
The Recall Score is:  0.8581560283687943
The Mean of Response Variable is:  0.5595238095238095


####**K-NEARESET NEIGHBORS**

In [37]:
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [38]:
y_test_pred=knn.predict(x_test)
confusion_matrix(y_test,y_test_pred)

array([[48, 63],
       [55, 86]])

In [39]:
print("The Accuracy Score is: ",accuracy_score(y_test,y_test_pred))
print("The Precision Score is: ",precision_score(y_test,y_test_pred))
print("The Recall Score is: ",recall_score(y_test,y_test_pred))
print("The Mean of Response Variable is: ",np.mean(y_test))

The Accuracy Score is:  0.5317460317460317
The Precision Score is:  0.5771812080536913
The Recall Score is:  0.6099290780141844
The Mean of Response Variable is:  0.5595238095238095
